name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade pip & install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: |
          python -u run.py strings.xml target_langs vi hi fr ja ko

      - name: Prepare out/ directory and copy XMLs
        run: |
          mkdir -p out
          cp -u strings-*.xml out/ || echo "No strings-*.xml found"

      - name: Commit and push out/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add out/

          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "Update out/ with strings-*.xml"
          git push origin HEAD:main
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
